version: "3.8"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: "free-bitcoin-history"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - free-bitcoin-history-dev-db:/var/lib/mysql
volumes:
  free-bitcoin-history-dev-db:
